import Head from 'next/head'
import Csv from './components/Csv'
import Attendance from './components/getAttendance'
import Admin from './components/Admin'
import NavBar from './components/NavBar';
import StudentLogin from './studentLogin';


export default function Home() {


  return (
    <>
      <Head>
        <title>IT CUSAT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <div className="as">


        <StudentLogin />

        {/* <Csv/> */}

        
      </div>
      </>
    </>
  )
}

